# Generated by Django 5.1.2 on 2024-10-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_video_num_likes_alter_video_num_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbmail',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='media/thumbnails/', verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='media/videos/', verbose_name='Vídeo'),
        ),
    ]
